In [2]:
import pandas as pd   # importing library 
import numpy as np

In [3]:
dataset= pd.read_csv("insurance.csv")  # function of pandas used to load the data
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset) #to create dummies value for categorical text
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [5]:
dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false
dataset

C:\Users\jayas\AppData\Local\Temp\ipykernel_23936\2063786219.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [6]:
dataset = dataset.drop(columns=["sex_female", "smoker_no"])# drop columns from the dataset
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]  # split input and output to get input from dataset 
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[['charges']] # get output from dataset
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split  # sklearn library for machine learning
x_train,x_test,y_train,y_test = train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.model_selection import GridSearchCV # built model for grid search
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','sigmoid'],
            'C':[10,3000000,1000,]}
grid= GridSearchCV(SVR(),param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 3000000, 1000],
                         'kernel': ['rbf', 'poly', 'sigmoid']},
             verbose=3)

In [13]:
re=grid.cv_results_ # print best parameter after tuning
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000000, 'kernel': 'rbf'}:

In [14]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.161893,0.005564,0.086490,0.010792,10,rbf,"{'C': 10, 'kernel': 'rbf'}",-4.547724e-02,-1.333561e-02,-1.517906e-01,-1.519670e-01,-1.394476e-01,-1.004036e-01,0.059028,3
1,0.122447,0.008986,0.029654,0.002617,10,poly,"{'C': 10, 'kernel': 'poly'}",-1.342162e-01,2.678185e-02,-2.129786e-01,-2.374531e-01,-1.595822e-01,-1.434897e-01,0.092731,6
2,0.158737,0.005042,0.037817,0.002721,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",-4.287667e-02,-3.951154e-02,-1.501536e-01,-1.384923e-01,-1.433956e-01,-1.028859e-01,0.050518,4
3,7.569257,2.371188,0.074516,0.004571,3000000,rbf,"{'C': 3000000, 'kernel': 'rbf'}",8.457239e-01,8.111399e-01,8.189799e-01,8.068777e-01,7.585941e-01,8.082631e-01,0.028268,1
4,114.258039,27.769485,0.021128,0.004457,3000000,poly,"{'C': 3000000, 'kernel': 'poly'}",8.345358e-01,8.202372e-01,8.194797e-01,7.951530e-01,7.568663e-01,8.052544e-01,0.027305,2
5,0.161520,0.003476,0.040555,0.001834,3000000,sigmoid,"{'C': 3000000, 'kernel': 'sigmoid'}",-8.436768e+06,-8.389099e+06,-7.072735e+06,-8.785023e+06,-6.409044e+06,-7.818534e+06,914848.002147,9
6,0.156165,0.007614,0.076159,0.002117,1000,rbf,"{'C': 1000, 'kernel': 'rbf'}",-1.914218e-01,2.196241e-02,-2.465903e-01,-2.648133e-01,-1.749354e-01,-1.711597e-01,0.102158,7
7,0.182915,0.006522,0.026905,0.002372,1000,poly,"{'C': 1000, 'kernel': 'poly'}",-1.596096e-01,7.393986e-02,-1.916570e-01,-2.222947e-01,-1.401642e-01,-1.279571e-01,0.104757,5
8,0.155212,0.005315,0.035568,0.001705,1000,sigmoid,"{'C': 1000, 'kernel': 'sigmoid'}",-1.141295e+00,-1.269703e+00,-1.074688e+00,-1.221982e+00,-1.154634e+00,-1.172460e+00,0.067464,8

In [15]:
import pickle   # store the model
filename = "finalized_model_svr_grid_regression.sav" 
pickle.dump(grid,open(filename,"wb"))

In [18]:
load_model=pickle.load(open("finalized_model_svr_grid_regression.sav" ,"rb")) # load the model from the file
result=load_model.predict([[50,30.970,3,1,0]])

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

In [19]:
result

array([10602.11248154])