In [1]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\jayas\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\jayas\anaconda3\lib\site-packages (from lightgbm) (2.1.3)
Requirement already satisfied: scipy in c:\users\jayas\anaconda3\lib\site-packages (from lightgbm) (1.15.3)

In [2]:
import pandas as pd # import library 
import numpy as np
import lightgbm as lgb

In [3]:
dataset= pd.read_csv("insurance.csv")  # function of pandas used to load the data
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset) #to create dummies value for categorical text
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [5]:
dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false
dataset

C:\Users\jayas\AppData\Local\Temp\ipykernel_23132\2063786219.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [6]:
dataset = dataset.drop(columns=["sex_female", "smoker_no"])# drop columns from the dataset
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]  # split input and output to get input from dataset 
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']] # get output from dataset
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [49]:
from lightgbm import LGBMRegressor 
from sklearn.model_selection import GridSearchCV # built model for grid search and cross validation
param_grid={'random_state':[10,10,15],'n_estimators':[100,0.1,0.2],'learning_rate':[0.05,0.8,0.1]}
grid= GridSearchCV( LGBMRegressor(),param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000310 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 313
[LightGBM] [Info] Number of data points in the train set: 1338, number of used features: 5
[LightGBM] [Info] Start training from score 13270.422260

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
90 fits failed out of a total of 135.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\sklearn.py", line 1398, in fit
    super().fit(
    ~~~~~~~~~~~^
        X,
        ^^
    ...<11 lines>...
        init_model=init_model,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\sklearn.py", line 1049, in fit
    self._Booster = train(
                    ~~~~~^
        params=params,
        ^^^^^^^^^^^^^^
    ...<6 lines>...
        callbacks=callbacks,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\engine.py", line 297, in train
    booster = Booster(params=params, train_set=train_set)
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 3656, in __init__
    train_set.construct()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 2590, in construct
    self._lazy_init(
    ~~~~~~~~~~~~~~~^
        data=self.data,
        ^^^^^^^^^^^^^^^
    ...<9 lines>...
        position=self.position,
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 2187, in _lazy_init
    self.__init_from_np2d(data, params_str, ref_dataset)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 2318, in __init_from_np2d
    _safe_call(
    ~~~~~~~~~~^
        _LIB.LGBM_DatasetCreateFromMat(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
        )
        ^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 313, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode("utf-8"))
lightgbm.basic.LightGBMError: Parameter num_iterations should be of type int, got "0.1"

--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\sklearn.py", line 1398, in fit
    super().fit(
    ~~~~~~~~~~~^
        X,
        ^^
    ...<11 lines>...
        init_model=init_model,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\sklearn.py", line 1049, in fit
    self._Booster = train(
                    ~~~~~^
        params=params,
        ^^^^^^^^^^^^^^
    ...<6 lines>...
        callbacks=callbacks,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\engine.py", line 297, in train
    booster = Booster(params=params, train_set=train_set)
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 3656, in __init__
    train_set.construct()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 2590, in construct
    self._lazy_init(
    ~~~~~~~~~~~~~~~^
        data=self.data,
        ^^^^^^^^^^^^^^^
    ...<9 lines>...
        position=self.position,
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 2187, in _lazy_init
    self.__init_from_np2d(data, params_str, ref_dataset)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 2318, in __init_from_np2d
    _safe_call(
    ~~~~~~~~~~^
        _LIB.LGBM_DatasetCreateFromMat(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
        )
        ^
    )
    ^
  File "C:\Users\jayas\anaconda3\Lib\site-packages\lightgbm\basic.py", line 313, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode("utf-8"))
lightgbm.basic.LightGBMError: Parameter num_iterations should be of type int, got "0.2"

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.84843726 0.84843726 0.84843726        nan        nan        nan
        nan        nan        nan 0.76653159 0.76653159 0.76653159
        nan        nan        nan        nan        nan        nan
 0.83695252 0.83695252 0.83695252        nan        nan        nan
        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=LGBMRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.05, 0.8, 0.1],
                         'n_estimators': [100, 0.1, 0.2],
                         'random_state': [10, 10, 15]},
             verbose=3)

In [50]:
re=grid.cv_results_ # print best parameter after tuning
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'learning_rate': 0.05, 'n_estimators': 100, 'random_state': 10}:

In [51]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_n_estimators,param_random_state,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.389041,0.043921,0.005243,0.001014,0.05,100.0,10,"{'learning_rate': 0.05, 'n_estimators': 100, '...",0.868272,0.794835,0.883145,0.838226,0.857708,0.848437,0.030533,1
1,0.325449,0.037496,0.004450,0.000515,0.05,100.0,10,"{'learning_rate': 0.05, 'n_estimators': 100, '...",0.868272,0.794835,0.883145,0.838226,0.857708,0.848437,0.030533,1
2,0.300635,0.007331,0.003952,0.000214,0.05,100.0,15,"{'learning_rate': 0.05, 'n_estimators': 100, '...",0.868272,0.794835,0.883145,0.838226,0.857708,0.848437,0.030533,1
3,0.002467,0.000085,0.000000,0.000000,0.05,0.1,10,"{'learning_rate': 0.05, 'n_estimators': 0.1, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
4,0.002521,0.000239,0.000000,0.000000,0.05,0.1,10,"{'learning_rate': 0.05, 'n_estimators': 0.1, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
5,0.002540,0.000212,0.000000,0.000000,0.05,0.1,15,"{'learning_rate': 0.05, 'n_estimators': 0.1, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
6,0.002549,0.000268,0.000000,0.000000,0.05,0.2,10,"{'learning_rate': 0.05, 'n_estimators': 0.2, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
7,0.002353,0.000073,0.000000,0.000000,0.05,0.2,10,"{'learning_rate': 0.05, 'n_estimators': 0.2, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
8,0.002568,0.000303,0.000000,0.000000,0.05,0.2,15,"{'learning_rate': 0.05, 'n_estimators': 0.2, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
9,0.269718,0.016144,0.004024,0.000327,0.80,100.0,10,"{'learning_rate': 0.8, 'n_estimators': 100, 'r...",0.781791,0.686619,0.799976,0.787156,0.777116,0.766532,0.040681,7
10,0.289592,0.026229,0.003752,0.000127,0.80,100.0,10,"{'learning_rate': 0.8, 'n_estimators': 100, 'r...",0.781791,0.686619,0.799976,0.787156,0.777116,0.766532,0.040681,7
11,0.273176,0.002326,0.004165,0.000720,0.80,100.0,15,"{'learning_rate': 0.8, 'n_estimators': 100, 'r...",0.781791,0.686619,0.799976,0.787156,0.777116,0.766532,0.040681,7
12,0.002861,0.000310,0.000000,0.000000,0.80,0.1,10,"{'learning_rate': 0.8, 'n_estimators': 0.1, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
13,0.002536,0.000258,0.000000,0.000000,0.80,0.1,10,"{'learning_rate': 0.8, 'n_estimators': 0.1, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
14,0.002684,0.000306,0.000000,0.000000,0.80,0.1,15,"{'learning_rate': 0.8, 'n_estimators': 0.1, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
15,0.002283,0.000098,0.000000,0.000000,0.80,0.2,10,"{'learning_rate': 0.8, 'n_estimators': 0.2, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
16,0.002429,0.000220,0.000000,0.000000,0.80,0.2,10,"{'learning_rate': 0.8, 'n_estimators': 0.2, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
17,0.002408,0.000163,0.000000,0.000000,0.80,0.2,15,"{'learning_rate': 0.8, 'n_estimators': 0.2, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
18,0.194265,0.069672,0.003742,0.000141,0.10,100.0,10,"{'learning_rate': 0.1, 'n_estimators': 100, 'r...",0.857835,0.776793,0.868698,0.831484,0.849952,0.836953,0.032440,4
19,0.144195,0.058818,0.003728,0.000142,0.10,100.0,10,"{'learning_rate': 0.1, 'n_estimators': 100, 'r...",0.857835,0.776793,0.868698,0.831484,0.849952,0.836953,0.032440,4
20,0.169311,0.061148,0.003784,0.000221,0.10,100.0,15,"{'learning_rate': 0.1, 'n_estimators': 100, 'r...",0.857835,0.776793,0.868698,0.831484,0.849952,0.836953,0.032440,4
21,0.002503,0.000532,0.000000,0.000000,0.10,0.1,10,"{'learning_rate': 0.1, 'n_estimators': 0.1, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
22,0.002477,0.000121,0.000000,0.000000,0.10,0.1,10,"{'learning_rate': 0.1, 'n_estimators': 0.1, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
23,0.002540,0.000325,0.000000,0.000000,0.10,0.1,15,"{'learning_rate': 0.1, 'n_estimators': 0.1, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
24,0.002645,0.000266,0.000000,0.000000,0.10,0.2,10,"{'learning_rate': 0.1, 'n_estimators': 0.2, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
25,0.002772,0.000383,0.000000,0.000000,0.10,0.2,10,"{'learning_rate': 0.1, 'n_estimators': 0.2, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
26,0.002821,0.000288,0.000000,0.000000,0.10,0.2,15,"{'learning_rate': 0.1, 'n_estimators': 0.2, 'r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,10

In [52]:
import pickle   # store the model
filename = "finalized_model_LG_BOOST_grid.sav" 
pickle.dump(grid,open(filename,"wb"))

In [53]:
load_model=pickle.load(open("finalized_model_LG_BOOST_grid.sav" ,"rb")) # load the model from the file
result=load_model.predict([[32,28.880,0,1,0]])

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [54]:
result

array([3514.75349338])